/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package liuwei.job.core.cron;

public class App {

    public static void main(String[] args) {
        CronExpDescriptor cronExpDescriptor = new CronExpDescriptor();
        System.out.println(cronExpDescriptor.nextTriggerDate("0 0 /5 * * *"));
    }
}
